language: csharp
os:
  - linux
  - osx
mono:
  - latest
env:
  matrix:
    - CONFIGURATION=Release PLATFORM=AnyCPU
    - CONFIGURATION=Release PLATFORM=x86
    - CONFIGURATION=Release PLATFORM=x64
matrix:
  fast_finish: true
solution: Core2D.mono.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gtk-sharp2 ; fi
  - mono .nuget/nuget.exe restore Core2D.mono.sln
  - mono .nuget/nuget.exe install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration="$CONFIGURATION" /p:Platform="$PLATFORM" Core2D.mono.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/Core2D.UnitTests/bin/"$PLATFORM"/"$CONFIGURATION"/Core2D.UnitTests.dll
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./tests/FileSystem.DotNetFx.UnitTests/bin/"$PLATFORM"/"$CONFIGURATION"/FileSystem.DotNetFx.UnitTests.dll
