language: csharp
os:
  - linux
  - osx
mono:
  - latest
env:
  matrix:
    - CONFIGURATION=Release PLATFORM=AnyCPU
    - CONFIGURATION=Release PLATFORM=x86
    - CONFIGURATION=Release PLATFORM=x64
matrix:
  fast_finish: true
script:
  - ./build.sh --target "Travis" --platform "$PLATFORM" --configuration "$CONFIGURATION"
cache:
  directories:
    - packages
    - tools