language: csharp
os:
  - linux
  - osx
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono:
  - latest
dotnet: 1.0.1
script:
  - ./build.sh --target "Travis" --platform "AnyCPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6608b67ed885b53fcc02
    on_success: change
    on_failure: always
    on_start: never