version: 0.1.{build}
skip_tags: true
os: Visual Studio 2015
configuration:
- Debug
- Release
before_build:
- cmd: >-
    git submodule update --init
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    restore.cmd
build:
  project: Core2D.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a Core2D-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D\bin\%CONFIGURATION%\*
    7z a Core2D.Avalonia-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D.Avalonia\bin\%CONFIGURATION%\*
    7z a Core2D.Avalonia.Cairo-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D.Avalonia.Cairo\bin\%CONFIGURATION%\*
    7z a Core2D.Avalonia.Direct2D-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D.Avalonia.Direct2D\bin\%CONFIGURATION%\*
    7z a Core2D.Avalonia.Skia-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D.Avalonia.Skia\bin\%CONFIGURATION%\*
    7z a Core2D.Wpf-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\src\Core2D.Wpf\bin\%CONFIGURATION%\*
    appveyor PushArtifact Core2D-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
    appveyor PushArtifact Core2D.Avalonia-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
    appveyor PushArtifact Core2D.Avalonia.Cairo-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
    appveyor PushArtifact Core2D.Avalonia.Direct2D-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
    appveyor PushArtifact Core2D.Avalonia.Skia-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
    appveyor PushArtifact Core2D.Wpf-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  auth_token:
    secure: 6jHUhHqAmyx5NOZWctCi0A72lGgaGxhT5tRWnBNMz1JYHOgg1PEID1DFEG1jiQeO
  artifact: /.*\.zip/
  prerelease: true
  on:
    branch: master
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/cc9eb0e869ca5a539718
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
