os: Visual Studio 2017
platform:
- AnyCPU
configuration:
- Release
install:
  - if not exist vc_redist.x86.exe appveyor DownloadFile https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe -FileName "vc_redist.x86.exe"
  - if not exist vc_redist.x64.exe appveyor DownloadFile https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe -FileName "vc_redist.x64.exe"
  - vc_redist.x86.exe /install /passive /norestart
  - vc_redist.x64.exe /install /passive /norestart
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform $env:platform -Configuration $env:configuration
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/1ff736226b47ccf79930
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\zip\*.zip
cache:
  - vc_redist.x86.exe
  - vc_redist.x64.exe
