os: Visual Studio 2017
platform:
- AnyCPU
configuration:
- Release
install:
  - if not exist gtk-sharp-2.12.26.msi appveyor DownloadFile http://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi
  - if not exist dotnet-1.0.1.exe appveyor DownloadFile https://go.microsoft.com/fwlink/?linkid=843448 -FileName "dotnet-1.0.1.exe"
  - if not exist vc_redist.x86.exe appveyor DownloadFile https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe -FileName "vc_redist.x86.exe"
  - if not exist vc_redist.x64.exe appveyor DownloadFile https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe -FileName "vc_redist.x64.exe"
  - ps: Start-Process -FilePath "msiexec" -ArgumentList "/i gtk-sharp-2.12.26.msi /quiet /qn /norestart" -Wait -Passthru
  - ps: Start-Process -FilePath "dotnet-1.0.1.exe" -ArgumentList "/quiet" -Wait -Passthru
  - ps: Start-Process -FilePath "vc_redist.x86.exe" -ArgumentList " /extract:vc_redist.x86 /quiet /passive" -Wait -Passthru
  - ps: Start-Process -FilePath "msiexec" -ArgumentList "/i vc_redist.x86\vc_red.msi /quiet /qn /norestart TARGETDIR=vc_redist.x86\msvcr" -Wait -Passthru
  - ps: Start-Process -FilePath "vc_redist.x64.exe" -ArgumentList " /extract:vc_redist.x64 /quiet /passive" -Wait -Passthru
  - ps: Start-Process -FilePath "msiexec" -ArgumentList "/i vc_redist.x64\vc_red.msi /quiet /qn /norestart TARGETDIR=vc_redist.x64\msvcr" -Wait -Passthru
  - cmd: set PATH=%programfiles(x86)%\GtkSharp\2.12\bin\;%PATH%
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform $env:platform -Configuration $env:configuration
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/1ff736226b47ccf79930
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\zip\*.zip
cache:
  - gtk-sharp-2.12.26.msi
  - dotnet-1.0.1.exe
  - vc_redist.x86.exe
  - vc_redist.x64.exe
