version: 0.1.0.{build}
skip_tags: true
os: Visual Studio 2015
platform:
- AnyCPU
- x86
- x64
configuration:
- Release
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform $env:platform -Configuration $env:configuration
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/cc9eb0e869ca5a539718
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
cache:
- packages -> src\**\packages.config, dependencies\**\packages.config, tests\**\packages.config
- tools -> build.cake, tools\packages.config