pool:
  vmImage: 'Hosted VS2017'
steps:
- script: |
    dotnet --info
    dotnet tool install -g Cake.Tool --version 0.30.0
    set PATH=%PATH%;%USERPROFILE%\.dotnet\tools
    dotnet cake build.cake -Target="Build" -Platform="Any CPU" -Configuration="Release"
