pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: 'dotnet --info'
- script: 'dotnet tool install -g Cake.Tool --version 0.30.0'
- script: 'set PATH=%PATH%;%USERPROFILE%\.dotnet\tools'
- script: 'dotnet cake build.cake -Target="Build" -Platform="$(buildPlatform)" -Configuration="$(buildConfiguration)"'
