jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet cake build.cake -Target="Azure-Linux" -Platform="Any CPU" -Configuration="Release"
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet cake build.cake -Target="Azure-macOS" -Platform="Any CPU" -Configuration="Release"
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      set COREHOST_TRACE=0
      set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      set DOTNET_CLI_TELEMETRY_OPTOUT=1
      where dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      set PATH=%PATH%;%USERPROFILE%\.dotnet\tools
      dotnet cake build.cake -Target="Azure-Windows" -Platform="Any CPU" -Configuration="Release"
- job: Linux_CoreRT
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet publish ./src/Core2D.UI.Avalonia/Core2D.UI.Avalonia.csproj -r linux-x64 -c Release -f netcoreapp2.1 -p:CoreRT=True
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'/src/Core2D.UI.Avalonia/bin/AnyCPU/Release/netcoreapp2.1/linux-x64/native'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Core2D.UI.Avalonia-native-linux-x64-$(Build.BuildId).zip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'CoreRT-Linux'
- job: macOS_CoreRT
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet publish ./src/Core2D.UI.Avalonia/Core2D.UI.Avalonia.csproj -r osx-x64 -c Release -f netcoreapp2.1 -p:CoreRT=True
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'/src/Core2D.UI.Avalonia/bin/AnyCPU/Release/netcoreapp2.1/osx-x64/native'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Core2D.UI.Avalonia-native-osx-x64-$(Build.BuildId).zip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'CoreRT-macOS'
- job: Windows_CoreRT
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.401'
  - script: |
      set COREHOST_TRACE=0
      set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      set DOTNET_CLI_TELEMETRY_OPTOUT=1
      where dotnet
      dotnet --info
      dotnet publish .\src\Core2D.UI.Avalonia\Core2D.UI.Avalonia.csproj -r win-x64 -c Release -f netcoreapp2.1 -p:CoreRT=True
      copy c:\Users\%USERNAME%\.nuget\packages\skiasharp\1.60.0\runtimes\win7-x64\native\libSkiaSharp.dll src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
      copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.15.26706\x64\Microsoft.VC141.CRT\msvcp140.dll" src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
      copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.15.26706\x64\Microsoft.VC141.CRT\vcruntime140.dll" src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
      copy "C:\Program Files (x86)\Google\Chrome\Application\68.0.3440.106\d3dcompiler_47.dll" src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
      copy "C:\Program Files (x86)\Google\Chrome\Application\68.0.3440.106\libegl.dll" src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
      copy "C:\Program Files (x86)\Google\Chrome\Application\68.0.3440.106\libglesv2.dll" src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'\src\Core2D.UI.Avalonia\bin\AnyCPU\Release\netcoreapp2.1\win-x64\native'
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Core2D.UI.Avalonia-native-win-x64-$(Build.BuildId).zip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'CoreRT-Windows'
