version: 2
jobs:
  build:
    working_directory: ~/Core2D
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore apps/Core2D.Avalonia.NetCore
      - run: dotnet build apps/Core2D.Avalonia.NetCore/Core2D.Avalonia.NetCore.csproj
