version: 2
jobs:
  build:
    working_directory: ~/Core2D
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore apps/Core2D.Avalonia
      - run: dotnet build apps/Core2D.Avalonia/Core2D.Avalonia.csproj
      - run: dotnet publish apps/Core2D.Avalonia/Core2D.Avalonia.csproj -c Release -r win7-x64 -o bin/win7-x64
      - store_artifacts:
          path: ~/Core2D/apps/Core2D.Avalonia/bin/win7-x64
          destination: Core2D.Avalonia-win7-x64
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/18bc2743c91ff21c0246
