version: 2
jobs:
  build:
    working_directory: ~/Core2D
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore apps/Core2D.Avalonia
      - run: dotnet build apps/Core2D.Avalonia/Core2D.Avalonia.csproj
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/18bc2743c91ff21c0246
