name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build Release
      run: dotnet build -c Release
    - name: Test Release
      run: dotnet test -c Release

  publish-windows:
    name: Publish windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      run: dotnet publish -c Release -f netcoreapp3.1 -r win7-x64 -o ./artifacts/Core2D-netcoreapp3.1-win7-x64 ./src/Core2D/Core2D.csproj
    - name: Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Core2D-netcoreapp3.1-win7-x64
        path: ./artifacts/Core2D-netcoreapp3.1-win7-x64

  publish-ubuntu:
    name: Publish ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      run: dotnet publish -c Release -f netcoreapp3.1 -r ubuntu.14.04-x64 -o ./artifacts/Core2D-netcoreapp3.1-ubuntu.14.04-x64 ./src/Core2D/Core2D.csproj
    - name: Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Core2D-netcoreapp3.1-ubuntu.14.04-x64
        path: ./artifacts/Core2D-netcoreapp3.1-ubuntu.14.04-x64

  publish-macos:
    name: Publish macos-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      run: dotnet publish -c Release -f netcoreapp3.1 -r osx.10.12-x64 -o ./artifacts/Core2D-netcoreapp3.1-osx.10.12-x64 ./src/Core2D/Core2D.csproj
    - name: Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Core2D-netcoreapp3.1-osx.10.12-x64
        path: ./artifacts/Core2D-netcoreapp3.1-osx.10.12-x64
