name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0

    - name: Install workload
      run: dotnet workload install wasm-tools wasm-experimental

    - name: Publish .NET Project
      run: dotnet publish src/Core2D.Web/Core2D.Web.csproj -c Release -o release --nologo

    - name: Change base-tag in index.html from / to Core2D
      run: sed -i 's/<base href="\/" \/>/<base href="\/Core2D\/" \/>/g' src/Core2D.Web/bin/Release/net7.0/browser-wasm/AppBundle/index.html

    - name: copy index.html to 404.html
      run: cp src/Core2D.Web/bin/Release/net7.0/browser-wasm/AppBundle/index.html src/Core2D.Web/bin/Release/net7.0/browser-wasm/AppBundle/404.html

    - name: Add .nojekyll file
      run: touch src/Core2D.Web/bin/Release/net7.0/browser-wasm/AppBundle/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: src/Core2D.Web/bin/Release/net7.0/browser-wasm/AppBundle
